version: "3.8"

services:
  postgres:
    image: apache/age
    container_name: postgres-age-container
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPW
      POSTGRES_DB: postgresDB
    ports:
      - "5455:5432"
    networks:
      - my_network

  fastapi:
    build:
      context: .
    container_name: fastapi-container
    environment:
      DB_HOST: postgres-age-container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
